name: Testing

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - name: Install Boost Test
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
             vcpkg install boost-test --triplet x64-windows
             echo "BUILD_TYPE=Release" >> $GITHUB_ENV
          else
             vcpkg install boost-test
             echo "BUILD_TYPE=Debug" >> $GITHUB_ENV
          fi
          vcpkg integrate install
      - name: Configure
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
             cmake -S. -Bbuild -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -Ax64
          else
             cmake -S. -Bbuild -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCMAKE_TOOLCHAIN_FILE="/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake"
          fi
      - name: Build
        run: |
          cmake --build build --config "$BUILD_TYPE"
      - name: Test
        run: |
          cd build
          ctest -C "$BUILD_TYPE" --output-on-failure --verbose
