name: Testing

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - name: Install Boost Test
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
             vcpkg install boost-test --triplet x64-windows
             echo "BUILD_TYPE=Release" >> $GITHUB_ENV
          else
             vcpkg install boost-test
             echo "BUILD_TYPE=Debug" >> $GITHUB_ENV
          fi
          vcpkg integrate install
      - name: Build
        run: |
          mkdir build && cd build && cmake ../ && make
      - name: Test
        run: |
          ./tests/unit_tests
